### ISSUE TITLE
Consider using `setupFiles`

### ISSUE THREAD

**Issue by fvictorio** [RyanHosseini/hardhat-jest#2]
I only skimmed the code, but as far as I can tell, this plugin needs all the files to explicitly `require` Hardhat. In typescript projects this is already necessary, but in js projects is not.

The builtin `test` task solves this by adding the `"hardaht/register"` module to the `require` option of Mocha. I think you can make something similar in jest with [`setupFiles`](https://jestjs.io/docs/configuration#setupfiles-array). I haven't tried it though.

**Comment by arianXdev** [comment]
Thank you so much for reviewing the code and helping @fvictorio,

Please correct me if I'm wrong,
Do you mean I need to pass `hardhat/register` as a path to `setupFiles` option?

```
const jestOptions = {
        setupFiles: ["hardhat/register"],
	watch: ...,
	watchAll: ...,
	bail: ...,
};
```
Am I right?

Appreciate your help.

**Comment by RyanHosseini** [comment]
>

**Comment by fvictorio** [comment]
Yes. I haven't tried it but it seems like it could work. If it works, you should have all the HRE fields globally available.

**Comment by arianXdev** [comment]
I just added `setupFiles`, Could you please take a look at [`develop` branch](https://github.com/RyanHosseini/hardhat-jest/tree/develop/src) and see?!

Thanks @fvictorio.

**Comment by fvictorio** [comment]
That looks fine, although I haven't tested it. The way to manually check that it works is, I think, to create a test file with:

```
it('test', async () => {
  console.log(network.name)
})
```

In the version in `main` you should get an error, but with that change you should see `hardhat` (or whatever network is selected).

**Comment by arianXdev** [comment]
Yes, that's right, It worked properly as you said 👌🏻
Thank you so much for your help @fvictorio 
Really appreciate your help!
