### ISSUE TITLE
 Linking failure in asm.js: Unexpected stdlib member

### ISSUE THREAD

**Issue by arianXdev** [RyanHosseini/hardhat-jest#4]
@fvictorio Excuse me, I've come across an issue when using Jest + Hardhat, and searched a lot about it, but I couldn't figure it out,
It would be my pleasure if you can help me solve it, Thanks,

When I run `npx hardhat jest`, I get this warning
```
(node:34981) V8: /home/user/Projects/spectre-decentralized-exchange/node_modules/rustbn.js/lib/index.asm.js:2 Linking failure in asm.js: Unexpected stdlib member
(Use `node --trace-warnings ...` to show where the warning was created)
(node:34987) V8: /home/user/Projects/spectre-decentralized-exchange/node_modules/rustbn.js/lib/index.asm.js:2 Linking failure in asm.js: Unexpected stdlib member
(Use `node --trace-warnings ...` to show where the warning was created)
```

I couldn't figure out what's the problem with it, it happens when it's a Hardhat project, if you use Jest in other ways inside of a Hardhat project, it throws the same warning, 

Do you know what's wrong or how can I solve it?! @fvictorio

Really appreciate your help.

**Comment by fvictorio** [comment]
I don't know what could be the reason. I've never seen that error, and it doesn't happen locally to me (node v14).

**Comment by arianXdev** [comment]
Very well, if you don't get the warning, that's great, I thought that it may be on behalf of Hardhat but it seems like it's just because of other reasons or some conflicts on my computer, anyway, Thank you @fvictorio 🙏🏻

**Comment by brett-petrusek** [comment]
I am also receiving this warning when running `npx hardhat test:jest` with node 16 rustbn version 0.2.0. This does not occur if I only run `npx jest`.
package.json:
```
{
    "name": "test-app",
    "description": "test app",
    "version": "0.0.1",
    "private": true,
    "dependencies": {
        "@aws-sdk/client-dynamodb": "^3.272.0",
        "@aws-sdk/client-s3": "^3.290.0",
        "@aws-sdk/client-sqs": "^3.272.0",
        "@aws-sdk/util-stream-node": "^3.290.0",
        "dotenv": "^16.0.3",
        "ethers": "^5.4.0",
        "hardhat": "^2.13.0",
        "hardhat-jest-plugin": "^0.0.6"
    },
    "devDependencies": {
        "@nomiclabs/hardhat-ethers": "^2.2.2",
        "aws-sdk-client-mock": "^2.1.0",
        "eslint": "^8.34.0",
        "eslint-config-standard": "^17.0.0",
        "eslint-plugin-import": "^2.27.5",
        "eslint-plugin-n": "^15.6.1",
        "eslint-plugin-promise": "^6.1.1",
        "jest": "^26.6.3"
    },
    "scripts": {
        "test": "jest"
    }
}
```
hardhat config
```
/**
* @type import('hardhat/config').HardhatUserConfig
*/
require("@nomiclabs/hardhat-ethers");
require("hardhat-jest-plugin");
module.exports = {
  solidity: "0.8.12",
  networks: {
    hardhat: {}
  }
};
```

**Comment by arianXdev** [comment]
> I am also receiving this warning when running `npx hardhat test:jest` with node 16 rustbn version 0.2.0. This does not occur if I only run `npx jest`. package.json:
>

@brett-petrusek Thanks for your comment, You're using [`hardhat-jest-plugin`](https://github.com/rryter/hardhat-jest-plugin) which is another Hardhat plugin created by somebody else, not me, It's actually another package which is not related to [`hardhat-jest`](https://npmjs.com/package/hardhat-jest) at all,
If you plan to use another package instead, I highly recommend you give [`hardhat-jest`](https://www.npmjs.com/package/hardhat-jest) a shot and if you get any problems, please let me know! Thank you.
