### ISSUE TITLE
Add jest as a peer dependency

### ISSUE THREAD

**Issue by fvictorio** [RyanHosseini/hardhat-jest#5]
Jest should be a peer dependency of the plugin. I'm not sure which range of versions should be supported though, but any version included should have the same interface in the part of the API that is being used.

Probably the easiest thing to do is to just use `^29.0.0`.

**Comment by arianXdev** [comment]
Thank you so much for your help again @fvictorio 🙏🏻
I just added Jest as a peer dependency.
