### ISSUE TITLE
Please consider adding a mock project/starter kit

### ISSUE THREAD

**Issue by Oni-giri** [RyanHosseini/hardhat-jest#6]
Hi,

Thanks for the plugin! I wanted to check Jest, but I had a hard time making it work out of the box. 

For instance, if you create a sample Hardhat project using the `npx hardhat ` prompt, add jest following your guide, you'll run into a `By default "node_modules" folder is ignored by transformers.`. This means a jest config is needed, you have to debug, add a test env, etc, etc. This makes it hard to switch to this plugin when everything is working with Mocha.

Therefore, please consider adding to your roadmap a starter project, as it would help jest-noobs like me to make the switch.

Cheers!

**Comment by arianXdev** [comment]
Hi @Oni-giri
Sorry for the late reply,

Thank you so much for your comment! I will definitely check it out and make it happen soon,
Please let me know if there are any further points.

**Comment by maoueh** [comment]
What would be an example `jest` Config to provide? I'm doing this now.

> his means a jest config is needed, you have to debug, add a test env, etc, etc

On it :)

**Comment by maoueh** [comment]
Ok see https://github.com/arianXdev/hardhat-jest/pull/7 for advancement
